#!/usr/bin/env bash

set -u

DRY_RUN=0
if [[ "${1-}" == "--dry-run" ]]; then
  DRY_RUN=1
elif [[ "${1-}" != "" ]]; then
  echo "Usage: $0 [--dry-run]" >&2
  exit 2
fi

REPO="$(gh repo view --json nameWithOwner --jq '.nameWithOwner')"
OWNER="${REPO%/*}"
NAME="${REPO#*/}"

if [[ "$DRY_RUN" -eq 1 ]]; then
  echo "C1: gh repo view --json nameWithOwner --jq '.nameWithOwner'"
  echo "C2: gh api \"repos/$OWNER/$NAME/branches/master/protection\" --jq '.required_status_checks.contexts'"
  echo "C3: gh api \"repos/$OWNER/$NAME/branches/master/protection\" --jq '.required_status_checks.strict'"
  echo "C4: gh api \"repos/$OWNER/$NAME/branches/master/protection\" --jq '.enforce_admins.enabled'"
  echo "C5: gh api \"repos/$OWNER/$NAME/branches/master/protection\" --jq '.allow_force_pushes.enabled'"
  echo "C6: gh api \"repos/$OWNER/$NAME/actions/workflows\" --jq '.workflows[] | select(.path==\".github/workflows/contract-gate.yml\") | .state'"
  echo "C7: gh api \"repos/$OWNER/$NAME/actions/workflows/contract-gate.yml/runs?per_page=1\" --jq '.workflow_runs[0] | {status, conclusion}'"
  exit 0
fi

PASS_COUNT=0
FAIL_COUNT=0

report_check() {
  local check_id="$1"
  local expected="$2"
  local actual="$3"

  if [[ "$actual" == "$expected" ]]; then
    echo "$check_id PASS"
    PASS_COUNT=$((PASS_COUNT + 1))
    return 0
  else
    echo "$check_id FAIL"
    echo "  expected: $expected"
    echo "  actual:   $actual"
    FAIL_COUNT=$((FAIL_COUNT + 1))
    return 1
  fi
}

# C1
C1_ACTUAL="$(gh repo view --json nameWithOwner --jq '.nameWithOwner')"
report_check "C1 Repo identity" "andrewmcadoo/athena" "$C1_ACTUAL"

# C2
C2_ACTUAL="$(gh api "repos/$OWNER/$NAME/branches/master/protection" --jq '.required_status_checks.contexts')"
report_check "C2 Required contexts" '["contract-verification"]' "$C2_ACTUAL"

# C3
C3_ACTUAL="$(gh api "repos/$OWNER/$NAME/branches/master/protection" --jq '.required_status_checks.strict')"
report_check "C3 Strict mode" "true" "$C3_ACTUAL"

# C4
C4_ACTUAL="$(gh api "repos/$OWNER/$NAME/branches/master/protection" --jq '.enforce_admins.enabled')"
report_check "C4 Admin enforcement" "true" "$C4_ACTUAL"

# C5
C5_ACTUAL="$(gh api "repos/$OWNER/$NAME/branches/master/protection" --jq '.allow_force_pushes.enabled')"
report_check "C5 Force pushes disabled" "false" "$C5_ACTUAL"

# C6
C6_ACTUAL="$(gh api "repos/$OWNER/$NAME/actions/workflows" --jq '.workflows[] | select(.path==".github/workflows/contract-gate.yml") | .state')"
report_check "C6 Workflow active" "active" "$C6_ACTUAL"

# C7
C7_JSON="$(gh api "repos/$OWNER/$NAME/actions/workflows/contract-gate.yml/runs?per_page=1" --jq '.workflow_runs[0] | {status, conclusion}' | jq -c '.')"
C7_STATUS="$(jq -r '.status' <<<"$C7_JSON")"
C7_CONCLUSION="$(jq -r '.conclusion' <<<"$C7_JSON")"
C7_ACTUAL="{\"status\":\"$C7_STATUS\",\"conclusion\":\"$C7_CONCLUSION\"}"
if [[ "$C7_STATUS" == "completed" && "$C7_CONCLUSION" == "success" ]]; then
  report_check "C7 Latest run success" '{"status":"completed","conclusion":"success"}' '{"status":"completed","conclusion":"success"}'
else
  report_check "C7 Latest run success" '{"status":"completed","conclusion":"success"}' "$C7_ACTUAL"
fi

AUDIT_TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
AUDITOR="$(whoami)"
SHA="$(git rev-parse HEAD)"

C1_RESULT="FAIL"
C2_RESULT="FAIL"
C3_RESULT="FAIL"
C4_RESULT="FAIL"
C5_RESULT="FAIL"
C6_RESULT="FAIL"
C7_RESULT="FAIL"

[[ "$C1_ACTUAL" == "andrewmcadoo/athena" ]] && C1_RESULT="PASS"
[[ "$C2_ACTUAL" == '["contract-verification"]' ]] && C2_RESULT="PASS"
[[ "$C3_ACTUAL" == "true" ]] && C3_RESULT="PASS"
[[ "$C4_ACTUAL" == "true" ]] && C4_RESULT="PASS"
[[ "$C5_ACTUAL" == "false" ]] && C5_RESULT="PASS"
[[ "$C6_ACTUAL" == "active" ]] && C6_RESULT="PASS"
[[ "$C7_STATUS" == "completed" && "$C7_CONCLUSION" == "success" ]] && C7_RESULT="PASS"

cat <<TEMPLATE
### Governance Audit Record
- Date (UTC): $AUDIT_TS
- Auditor: $AUDITOR
- Repo: andrewmcadoo/athena
- Commit SHA observed: $SHA
- C1 Repo identity: $C1_RESULT
- C2 Required contexts: $C2_RESULT
- C3 Strict mode: $C3_RESULT
- C4 Admin enforcement: $C4_RESULT
- C5 Force pushes disabled: $C5_RESULT
- C6 Workflow active: $C6_RESULT
- C7 Latest run success: $C7_RESULT
- Notes: Generated by research/adversarial-reward/governance/audit.sh
TEMPLATE

if [[ "$FAIL_COUNT" -gt 0 ]]; then
  exit 1
fi

exit 0
